# # this is not working and needs to be removed

client = Elasticsearch::Client.new hosts: [
    { host: 'my-protected-host',
      port: '9200',
      user: 'elastic',
      password: 'UnrddDXqg967nNVBYxDS',
      scheme: 'https'
    } ]

if Rails.env == 'production'
    url = ENV["SEARCHBOX_URL"]
    transport_options = { request: { timeout: 250 } }
    options = { hosts: url, retry_on_failure: true, transport_options: transport_options }
    Searchkick.client = Elasticsearch::Client.new(options)
end

    # Searchkick.client = Elasticsearch::Client.new(hosts: [
    #     "localhost:9200"], retry_on_failure: true, 
    #     transport_options: {request: {timeout: 250}})

# client = Elasticsearch::Client.new(
#     {host: '0.0.0.0',
#     port: '9200',
#     user: 'elastic',
#     password: 'UnrddDXqg967nNVBYxDS',
#     scheme: 'https'}
#   )

# # Colons and uppercase/lowercase don't matter when using
# # the 'ca_fingerprint' parameter
# CERT_FINGERPRINT = 'openssl x509 -fingerprint -sha256 -noout -in /dev/stdin'

# # Password for the 'elastic' user generated by Elasticsearch
# ELASTIC_PASSWORD = "UnrddDXqg967nNVBYxDS"

# client = Elasticsearch::Client.new(
#   host: "https://elastic:#{ELASTIC_PASSWORD}@localhost:9200",
#   transport_options: { ssl: { verify: false } },
#   ca_fingerprint: CERT_FINGERPRINT
# )

# ELASTIC_PASSWORD = 'UnrddDXqg967nNVBYxDS'
# client = Elasticsearch::Client.new(
#     host: "https://elastic:#{ELASTIC_PASSWORD}@localhost:9200",
#     transport_options: { ssl: { ca_path: 'app/elasticsearch/elastic-stack-ca.p12' } } 
#   )